# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 50, 300, 70))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans Normal ExtraBold")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_username.setGeometry(QtCore.QRect(150, 170, 500, 40))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans Normal SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setStyleSheet("padding-left: 10px;")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(150, 250, 500, 40))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans Normal SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("padding-left: 10px;")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(325, 350, 150, 45))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans Normal ExtraBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgb(21, 8, 204);\n"
"    background-color: rgb(21, 8, 204);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(21, 8, 204);\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top: 3px;\n"
"    padding-left: 3px;\n"
"}")
        self.pushButton_login.setObjectName("pushButton_login")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LOGIN"))
        self.lineEdit_username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton_login.setText(_translate("MainWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
